set = "RV32I"
width = 32

[types]
names = [
    "reg",
    "imm",
    "csr",
    "csri",
    "load",
    "store",
    "shift",
    "branch",
    "jump",
    "upper",
    "fence"
]
parts = [
    [
        "opcode",
        7,
        "u8",
    ],
    [
        "funct3",
        3,
        "u8",
    ],
    [
        "funct7",
        7,
        "u8",
    ],
    [
        "csr",
        12,
        "Register_csr"
    ],
    [
        "rd",
        5,
        "Register_int",
    ],
    [
        "rs1",
        5,
        "Register_int",
    ],
    [
        "rs2",
        5,
        "Register_int",
    ],
    [
        "shamt",
        5,
        "u8"
    ],
    [
        "imm",
        32,
        "VInt",
    ],
    [
        "pred",
        4,
        "Register_fence"
    ],
    [
        "succ",
        4,
        "Register_fence"
    ],
    [
        "discard",
        32,
        "VInt"
    ]
]

[type]
names = ["R", "I", "I_shift", "S", "B", "U", "J", "CSR", "CSRI", "Fence"]
R = [
    { name = "funct7", top = 6, bot = 0 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
I = [
    { name = "imm", top = 11, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
I_shift = [
    { name = "funct7", top = 6, bot = 0 },
    { name = "shamt", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
CSR = [
    { name = "csr", top = 11, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
CSRI = [
    { name = "csr", top = 11, bot = 0 },
    { name = "imm", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
S = [
    { name = "imm", top = 11, bot = 5 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "imm", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
B = [
    { name = "imm", top = 12, bot = 12 },
    { name = "imm", top = 10, bot = 5 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "imm", top = 4, bot = 1 },
    { name = "imm", top = 11, bot = 11 },
    { name = "opcode", top = 6, bot = 0 },
]
# U Different from risc-v spec, since for ASM representation, you would use it as imm[19:0] rather than imm[31:12]
U = [
    { name = "imm", top = 19, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
J = [
    { name = "imm", top = 20, bot = 20 },
    { name = "imm", top = 10, bot = 1 },
    { name = "imm", top = 11, bot = 11 },
    { name = "imm", top = 19, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
Fence = [
    { name = "discard", top = 3, bot = 0 },
    { name = "pred", top = 3, bot = 0 },
    { name = "succ", top = 3, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rd", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]

[reg]
type = "R"
[reg.repr]
default = "$name$ %rd%, %rs1%, %rs2%"
[reg.instructions]
add = { mask = 0xfe00707f, match = 0x33 }
sub = { mask = 0xfe00707f, match = 0x40000033 }
xor = { mask = 0xfe00707f, match = 0x4033 }
or = { mask = 0xfe00707f, match = 0x6033 }
and = { mask = 0xfe00707f, match = 0x7033 }
sll = { mask = 0xfe00707f, match = 0x1033 }
srl = { mask = 0xfe00707f, match = 0x5033 }
sra = { mask = 0xfe00707f, match = 0x40005033 }
slt = { mask = 0xfe00707f, match = 0x2033 }
sltu = { mask = 0xfe00707f, match = 0x3033 }


[imm]
type = "I"
[imm.repr]
default = "$name$ %rd%, %rs1%, %imm%"
jalr = "$name$ %rd%, %imm%(%rs1%)"
slti = "$name$ %rd%, %rs1%, %imm%"
sltiu = "$name$ %rd%, %rs1%, %imm%"
ecall = "$name$"
ebreak = "$name$"
[imm.instructions]
addi = { mask = 0x707f, match = 0x13 }
xori = { mask = 0x707f, match = 0x4013 }
ori = { mask = 0x707f, match = 0x6013 }
andi = { mask = 0x707f, match = 0x7013 }
jalr = { mask = 0x707f, match = 0x67 }
slti = { mask = 0x707f, match = 0x2013 }
sltiu = { mask = 0x707f, match = 0x3013 }
ecall = { mask = 0xffffffff, match = 0x73 }
ebreak = { mask = 0xffffffff, match = 0x100073 }

[csr]
type = "CSR"
[csr.repr]
default = "$name$ %rd%, %csr%, %rs1%"
[csr.instructions]
csrrc = { mask = 0x707f, match = 0x3073}
csrrs = { mask = 0x707f, match = 0x2073}
csrrw = { mask = 0x707f, match = 0x1073}

[csri]
type = "CSRI"
[csri.repr]
default = "$name$ %rd%, %csr%, %imm%"
[csri.instructions]
csrrci = { mask = 0x707f, match = 0x7073, unsigned = true }
csrrsi = { mask = 0x707f, match = 0x6073, unsigned = true }
csrrwi = { mask = 0x707f, match = 0x5073, unsigned = true }

[shift]
type = "I_shift"
[shift.repr]
default = "$name$ %rd%, %rs1%, %shamt%"
[shift.instructions]
slli = { mask = 0xfe00707f, match = 0x1013}
srai = { mask = 0xfe00707f, match = 0x40005013}
srli = { mask = 0xfe00707f, match = 0x5013}

[load]
type = "I"
[load.repr]
default = "$name$ %rd%, %imm%(%rs1%)"
[load.instructions]
lb = { mask = 0x707f, match = 0x3 }
lh = { mask = 0x707f, match = 0x1003 }
lw = { mask = 0x707f, match = 0x2003 }
lbu = { mask = 0x707f, match = 0x4003 }
lhu = { mask = 0x707f, match = 0x5003 }

[store]
type = "S"
[store.repr]
default = "$name$ %rs2%, %imm%(%rs1%)"
[store.instructions]
sb = { mask = 0x707f, match = 0x23 }
sh = { mask = 0x707f, match = 0x1023 }
sw = { mask = 0x707f, match = 0x2023 }

[branch]
type = "B"
[branch.repr]
default = "$name$ %rs1%, %rs2%, %imm%"
[branch.instructions]
beq = { mask = 0x707f, match = 0x63 }
bne = { mask = 0x707f, match = 0x1063 }
blt = { mask = 0x707f, match = 0x4063 }
bge = { mask = 0x707f, match = 0x5063 }
bltu = { mask = 0x707f, match = 0x6063 }
bgeu = { mask = 0x707f, match = 0x7063 }

[jump]
type = "J"
[jump.repr]
default = "$name$ %rd%, %imm%"
[jump.instructions]
jal = { mask = 0x7f, match = 0x6f }

[upper]
type = "U"
[upper.repr]
default = "$name$ %rd%, %imm%"
[upper.instructions]
lui = { mask = 0x7f, match = 0x37, unsigned = true }
auipc = { mask = 0x7f, match = 0x17, unsigned = true  }

[fence]
type = "Fence"
[fence.repr]
default = "fence %pred%, %succ%"
[fence.instructions]
fence = { mask = 0x707f, match = 0xf}

[register]
names = ["Register_int", "Register_csr", "Register_fence"]
number = 32
Register_int = [
    "zero",
    "ra",
    "sp",
    "gp",
    "tp",
    "t0",
    "t1",
    "t2",
    "s0",
    "s1",
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "s10",
    "s11",
    "t3",
    "t4",
    "t5",
    "t6",
]
[register.Register_csr]
0x001 = "fflags"
0x002 = "frm"
0x003 = "fcsr"
0x008 = "vstart"
0x009 = "vxsat"
0x00A = "vxrm"
0x00F = "vcsr"
0x011 = "ssp"
0x015 = "seed"
0x017 = "jvt"
0xC00 = "cycle"
0xC01 = "time"
0xC02 = "instret"
0xC03 = "hpmcounter3"
0xC04 = "hpmcounter4"
0xC05 = "hpmcounter5"
0xC06 = "hpmcounter6"
0xC07 = "hpmcounter7"
0xC08 = "hpmcounter8"
0xC09 = "hpmcounter9"
0xC0A = "hpmcounter10"
0xC0B = "hpmcounter11"
0xC0C = "hpmcounter12"
0xC0D = "hpmcounter13"
0xC0E = "hpmcounter14"
0xC0F = "hpmcounter15"
0xC10 = "hpmcounter16"
0xC11 = "hpmcounter17"
0xC12 = "hpmcounter18"
0xC13 = "hpmcounter19"
0xC14 = "hpmcounter20"
0xC15 = "hpmcounter21"
0xC16 = "hpmcounter22"
0xC17 = "hpmcounter23"
0xC18 = "hpmcounter24"
0xC19 = "hpmcounter25"
0xC1A = "hpmcounter26"
0xC1B = "hpmcounter27"
0xC1C = "hpmcounter28"
0xC1D = "hpmcounter29"
0xC1E = "hpmcounter30"
0xC1F = "hpmcounter31"
0xC20 = "vl"
0xC21 = "vtype"
0xC22 = "vlenb"
0x100 = "sstatus"
0x102 = "sedeleg"
0x103 = "sideleg"
0x104 = "sie"
0x105 = "stvec"
0x106 = "scounteren"
0x10A = "senvcfg"
0x10C = "sstateen0"
0x10D = "sstateen1"
0x10E = "sstateen2"
0x10F = "sstateen3"
0x120 = "scountinhibit"
0x140 = "sscratch"
0x141 = "sepc"
0x142 = "scause"
0x143 = "stval"
0x144 = "sip"
0x14D = "stimecmp"
0x150 = "siselect"
0x151 = "sireg"
0x152 = "sireg2"
0x153 = "sireg3"
0x155 = "sireg4"
0x156 = "sireg5"
0x157 = "sireg6"
0x15C = "stopei"
0x180 = "satp"
0x181 = "srmcfg"
0x5A8 = "scontext"
0x200 = "vsstatus"
0x204 = "vsie"
0x205 = "vstvec"
0x240 = "vsscratch"
0x241 = "vsepc"
0x242 = "vscause"
0x243 = "vstval"
0x244 = "vsip"
0x24D = "vstimecmp"
0x250 = "vsiselect"
0x251 = "vsireg"
0x252 = "vsireg2"
0x253 = "vsireg3"
0x255 = "vsireg4"
0x256 = "vsireg5"
0x257 = "vsireg6"
0x25C = "vstopei"
0x280 = "vsatp"
0x600 = "hstatus"
0x602 = "hedeleg"
0x603 = "hideleg"
0x604 = "hie"
0x605 = "htimedelta"
0x606 = "hcounteren"
0x607 = "hgeie"
0x608 = "hvien"
0x609 = "hvictl"
0x60A = "henvcfg"
0x60C = "hstateen0"
0x60D = "hstateen1"
0x60E = "hstateen2"
0x60F = "hstateen3"
0x643 = "htval"
0x644 = "hip"
0x645 = "hvip"
0x646 = "hviprio1"
0x647 = "hviprio2"
0x64A = "htinst"
0x680 = "hgatp"
0x6A8 = "hcontext"
0xE12 = "hgeip"
0xEB0 = "vstopi"
0xDA0 = "scountovf"
0xDB0 = "stopi"
0x007 = "utvt"
0x045 = "unxti"
0x046 = "uintstatus"
0x048 = "uscratchcsw"
0x049 = "uscratchcswl"
0x107 = "stvt"
0x145 = "snxti"
0x146 = "sintstatus"
0x148 = "sscratchcsw"
0x149 = "sscratchcswl"
0x307 = "mtvt"
0x345 = "mnxti"
0x346 = "mintstatus"
0x348 = "mscratchcsw"
0x349 = "mscratchcswl"
0x300 = "mstatus"
0x301 = "misa"
0x302 = "medeleg"
0x303 = "mideleg"
0x304 = "mie"
0x305 = "mtvec"
0x306 = "mcounteren"
0x308 = "mvien"
0x309 = "mvip"
0x30a = "menvcfg"
0x30C = "mstateen0"
0x30D = "mstateen1"
0x30E = "mstateen2"
0x30F = "mstateen3"
0x320 = "mcountinhibit"
0x340 = "mscratch"
0x341 = "mepc"
0x342 = "mcause"
0x343 = "mtval"
0x344 = "mip"
0x34a = "mtinst"
0x34b = "mtval2"
0x350 = "miselect"
0x351 = "mireg"
0x352 = "mireg2"
0x353 = "mireg3"
0x355 = "mireg4"
0x356 = "mireg5"
0x357 = "mireg6"
0x35c = "mtopei"
0x3a0 = "pmpcfg0"
0x3a1 = "pmpcfg1"
0x3a2 = "pmpcfg2"
0x3a3 = "pmpcfg3"
0x3a4 = "pmpcfg4"
0x3a5 = "pmpcfg5"
0x3a6 = "pmpcfg6"
0x3a7 = "pmpcfg7"
0x3a8 = "pmpcfg8"
0x3a9 = "pmpcfg9"
0x3aa = "pmpcfg10"
0x3ab = "pmpcfg11"
0x3ac = "pmpcfg12"
0x3ad = "pmpcfg13"
0x3ae = "pmpcfg14"
0x3af = "pmpcfg15"
0x3b0 = "pmpaddr0"
0x3b1 = "pmpaddr1"
0x3b2 = "pmpaddr2"
0x3b3 = "pmpaddr3"
0x3b4 = "pmpaddr4"
0x3b5 = "pmpaddr5"
0x3b6 = "pmpaddr6"
0x3b7 = "pmpaddr7"
0x3b8 = "pmpaddr8"
0x3b9 = "pmpaddr9"
0x3ba = "pmpaddr10"
0x3bb = "pmpaddr11"
0x3bc = "pmpaddr12"
0x3bd = "pmpaddr13"
0x3be = "pmpaddr14"
0x3bf = "pmpaddr15"
0x3c0 = "pmpaddr16"
0x3c1 = "pmpaddr17"
0x3c2 = "pmpaddr18"
0x3c3 = "pmpaddr19"
0x3c4 = "pmpaddr20"
0x3c5 = "pmpaddr21"
0x3c6 = "pmpaddr22"
0x3c7 = "pmpaddr23"
0x3c8 = "pmpaddr24"
0x3c9 = "pmpaddr25"
0x3ca = "pmpaddr26"
0x3cb = "pmpaddr27"
0x3cc = "pmpaddr28"
0x3cd = "pmpaddr29"
0x3ce = "pmpaddr30"
0x3cf = "pmpaddr31"
0x3d0 = "pmpaddr32"
0x3d1 = "pmpaddr33"
0x3d2 = "pmpaddr34"
0x3d3 = "pmpaddr35"
0x3d4 = "pmpaddr36"
0x3d5 = "pmpaddr37"
0x3d6 = "pmpaddr38"
0x3d7 = "pmpaddr39"
0x3d8 = "pmpaddr40"
0x3d9 = "pmpaddr41"
0x3da = "pmpaddr42"
0x3db = "pmpaddr43"
0x3dc = "pmpaddr44"
0x3dd = "pmpaddr45"
0x3de = "pmpaddr46"
0x3df = "pmpaddr47"
0x3e0 = "pmpaddr48"
0x3e1 = "pmpaddr49"
0x3e2 = "pmpaddr50"
0x3e3 = "pmpaddr51"
0x3e4 = "pmpaddr52"
0x3e5 = "pmpaddr53"
0x3e6 = "pmpaddr54"
0x3e7 = "pmpaddr55"
0x3e8 = "pmpaddr56"
0x3e9 = "pmpaddr57"
0x3ea = "pmpaddr58"
0x3eb = "pmpaddr59"
0x3ec = "pmpaddr60"
0x3ed = "pmpaddr61"
0x3ee = "pmpaddr62"
0x3ef = "pmpaddr63"
0x747 = "mseccfg"
0x7a0 = "tselect"
0x7a1 = "tdata1"
0x7a2 = "tdata2"
0x7a3 = "tdata3"
0x7a4 = "tinfo"
0x7a5 = "tcontrol"
0x7a8 = "mcontext"
0x7aa = "mscontext"
0x7b0 = "dcsr"
0x7b1 = "dpc"
0x7b2 = "dscratch0"
0x7b3 = "dscratch1"
0xB00 = "mcycle"
0xB02 = "minstret"
0xB03 = "mhpmcounter3"
0xB04 = "mhpmcounter4"
0xB05 = "mhpmcounter5"
0xB06 = "mhpmcounter6"
0xB07 = "mhpmcounter7"
0xB08 = "mhpmcounter8"
0xB09 = "mhpmcounter9"
0xB0A = "mhpmcounter10"
0xB0B = "mhpmcounter11"
0xB0C = "mhpmcounter12"
0xB0D = "mhpmcounter13"
0xB0E = "mhpmcounter14"
0xB0F = "mhpmcounter15"
0xB10 = "mhpmcounter16"
0xB11 = "mhpmcounter17"
0xB12 = "mhpmcounter18"
0xB13 = "mhpmcounter19"
0xB14 = "mhpmcounter20"
0xB15 = "mhpmcounter21"
0xB16 = "mhpmcounter22"
0xB17 = "mhpmcounter23"
0xB18 = "mhpmcounter24"
0xB19 = "mhpmcounter25"
0xB1A = "mhpmcounter26"
0xB1B = "mhpmcounter27"
0xB1C = "mhpmcounter28"
0xB1D = "mhpmcounter29"
0xB1E = "mhpmcounter30"
0xB1F = "mhpmcounter31"
0x321 = "mcyclecfg"
0x322 = "minstretcfg"
0x323 = "mhpmevent3"
0x324 = "mhpmevent4"
0x325 = "mhpmevent5"
0x326 = "mhpmevent6"
0x327 = "mhpmevent7"
0x328 = "mhpmevent8"
0x329 = "mhpmevent9"
0x32A = "mhpmevent10"
0x32B = "mhpmevent11"
0x32C = "mhpmevent12"
0x32D = "mhpmevent13"
0x32E = "mhpmevent14"
0x32F = "mhpmevent15"
0x330 = "mhpmevent16"
0x331 = "mhpmevent17"
0x332 = "mhpmevent18"
0x333 = "mhpmevent19"
0x334 = "mhpmevent20"
0x335 = "mhpmevent21"
0x336 = "mhpmevent22"
0x337 = "mhpmevent23"
0x338 = "mhpmevent24"
0x339 = "mhpmevent25"
0x33A = "mhpmevent26"
0x33B = "mhpmevent27"
0x33C = "mhpmevent28"
0x33D = "mhpmevent29"
0x33E = "mhpmevent30"
0x33F = "mhpmevent31"
0xF11 = "mvendorid"
0xF12 = "marchid"
0xF13 = "mimpid"
0xF14 = "mhartid"
0xF15 = "mconfigptr"
0xFB0 = "mtopi"
0x114 = "sieh"
0x154 = "siph"
0x15D = "stimecmph"
0x214 = "vsieh"
0x254 = "vsiph"
0x25D = "vstimecmph"
0x615 = "htimedeltah"
0x613 = "hidelegh"
0x618 = "hvienh"
0x61A = "henvcfgh"
0x655 = "hviph"
0x656 = "hviprio1h"
0x657 = "hviprio2h"
0x61C = "hstateen0h"
0x61D = "hstateen1h"
0x61E = "hstateen2h"
0x61F = "hstateen3h"
0xC80 = "cycleh"
0xC81 = "timeh"
0xC82 = "instreth"
0xC83 = "hpmcounter3h"
0xC84 = "hpmcounter4h"
0xC85 = "hpmcounter5h"
0xC86 = "hpmcounter6h"
0xC87 = "hpmcounter7h"
0xC88 = "hpmcounter8h"
0xC89 = "hpmcounter9h"
0xC8A = "hpmcounter10h"
0xC8B = "hpmcounter11h"
0xC8C = "hpmcounter12h"
0xC8D = "hpmcounter13h"
0xC8E = "hpmcounter14h"
0xC8F = "hpmcounter15h"
0xC90 = "hpmcounter16h"
0xC91 = "hpmcounter17h"
0xC92 = "hpmcounter18h"
0xC93 = "hpmcounter19h"
0xC94 = "hpmcounter20h"
0xC95 = "hpmcounter21h"
0xC96 = "hpmcounter22h"
0xC97 = "hpmcounter23h"
0xC98 = "hpmcounter24h"
0xC99 = "hpmcounter25h"
0xC9A = "hpmcounter26h"
0xC9B = "hpmcounter27h"
0xC9C = "hpmcounter28h"
0xC9D = "hpmcounter29h"
0xC9E = "hpmcounter30h"
0xC9F = "hpmcounter31h"
0x310 = "mstatush"
0x313 = "midelegh"
0x314 = "mieh"
0x318 = "mvienh"
0x319 = "mviph"
0x31A = "menvcfgh"
0x31C = "mstateen0h"
0x31D = "mstateen1h"
0x31E = "mstateen2h"
0x31F = "mstateen3h"
0x354 = "miph"
0x721 = "mcyclecfgh"
0x722 = "minstretcfgh"
0x723 = "mhpmevent3h"
0x724 = "mhpmevent4h"
0x725 = "mhpmevent5h"
0x726 = "mhpmevent6h"
0x727 = "mhpmevent7h"
0x728 = "mhpmevent8h"
0x729 = "mhpmevent9h"
0x72A = "mhpmevent10h"
0x72B = "mhpmevent11h"
0x72C = "mhpmevent12h"
0x72D = "mhpmevent13h"
0x72E = "mhpmevent14h"
0x72F = "mhpmevent15h"
0x730 = "mhpmevent16h"
0x731 = "mhpmevent17h"
0x732 = "mhpmevent18h"
0x733 = "mhpmevent19h"
0x734 = "mhpmevent20h"
0x735 = "mhpmevent21h"
0x736 = "mhpmevent22h"
0x737 = "mhpmevent23h"
0x738 = "mhpmevent24h"
0x739 = "mhpmevent25h"
0x73A = "mhpmevent26h"
0x73B = "mhpmevent27h"
0x73C = "mhpmevent28h"
0x73D = "mhpmevent29h"
0x73E = "mhpmevent30h"
0x73F = "mhpmevent31h"
0x740 = "mnscratch"
0x741 = "mnepc"
0x742 = "mncause"
0x744 = "mnstatus"
0x757 = "mseccfgh"
0xB80 = "mcycleh"
0xB82 = "minstreth"
0xB83 = "mhpmcounter3h"
0xB84 = "mhpmcounter4h"
0xB85 = "mhpmcounter5h"
0xB86 = "mhpmcounter6h"
0xB87 = "mhpmcounter7h"
0xB88 = "mhpmcounter8h"
0xB89 = "mhpmcounter9h"
0xB8A = "mhpmcounter10h"
0xB8B = "mhpmcounter11h"
0xB8C = "mhpmcounter12h"
0xB8D = "mhpmcounter13h"
0xB8E = "mhpmcounter14h"
0xB8F = "mhpmcounter15h"
0xB90 = "mhpmcounter16h"
0xB91 = "mhpmcounter17h"
0xB92 = "mhpmcounter18h"
0xB93 = "mhpmcounter19h"
0xB94 = "mhpmcounter20h"
0xB95 = "mhpmcounter21h"
0xB96 = "mhpmcounter22h"
0xB97 = "mhpmcounter23h"
0xB98 = "mhpmcounter24h"
0xB99 = "mhpmcounter25h"
0xB9A = "mhpmcounter26h"
0xB9B = "mhpmcounter27h"
0xB9C = "mhpmcounter28h"
0xB9D = "mhpmcounter29h"
0xB9E = "mhpmcounter30h"
0xB9F = "mhpmcounter31h"

[register.Register_fence]
0b0000 = "-"
0b0001 = "w"
0b0010 = "r"
0b0011 = "rw"
0b0100 = "o"
0b0101 = "ow"
0b0110 = "or"
0b0111 = "orw"
0b1000 = "i"
0b1001 = "iw"
0b1010 = "ir"
0b1011 = "irw"
0b1100 = "io"
0b1101 = "iow"
0b1110 = "ior"
0b1111 = "iorw"
